import type { Club, Event, Activity } from "./types"

export const mockClubs: Club[] = [
  {
    id: "1",
    name: "Laced of ART",
    nameEn: "Laced of ART",
    nameTh: "ชมรมศิลปะ",
    description: "Applied Artificial Technology Club - Exploring the intersection of art and technology",
    descriptionEn: "Applied Artificial Technology Club - Exploring the intersection of art and technology",
    descriptionTh: "ชมรมเทคโนโลยีศิลปะประยุกต์ - สำรวจจุดตัดระหว่างศิลปะและเทคโนโลยี",
    category: "arts",
    coverImage: "/art-technology-club-banner.jpg",
    logo: "/art-tech-logo-gold.jpg",
    memberCount: 156,
    contactEmail: "lacedofart@mfu.ac.th",
    socialLinks: {
      facebook: "https://facebook.com/lacedofart",
      instagram: "https://instagram.com/lacedofart",
    },
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "MFU Football Club",
    nameEn: "MFU Football Club",
    nameTh: "ชมรมฟุตบอล มฟล.",
    description: "Competitive football club representing MFU in inter-university tournaments",
    descriptionEn: "Competitive football club representing MFU in inter-university tournaments",
    descriptionTh: "ชมรมฟุตบอลแข่งขันเป็นตัวแทน มฟล. ในการแข่งขันระหว่างมหาวิทยาลัย",
    category: "sports",
    coverImage: "/university-football-team-stadium.jpg",
    memberCount: 89,
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    name: "Dance Crew",
    nameEn: "Dance Crew",
    nameTh: "ชมรมเต้น",
    description: "Modern and traditional dance performances",
    descriptionEn: "Modern and traditional dance performances",
    descriptionTh: "การแสดงเต้นสมัยใหม่และแบบดั้งเดิม",
    category: "arts",
    coverImage: "/dance-performance-stage-lights.jpg",
    memberCount: 67,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    name: "Music Band",
    nameEn: "Music Band",
    nameTh: "ชมรมดนตรี",
    description: "Live music performances and jam sessions",
    descriptionEn: "Live music performances and jam sessions",
    descriptionTh: "การแสดงดนตรีสดและเซสชั่นแจม",
    category: "music",
    coverImage: "/band-performance-concert.jpg",
    memberCount: 45,
    createdAt: "2024-01-20",
  },
  {
    id: "5",
    name: "Photography Club",
    nameEn: "Photography Club",
    nameTh: "ชมรมถ่ายภาพ",
    description: "Capturing moments and learning photography techniques",
    descriptionEn: "Capturing moments and learning photography techniques",
    descriptionTh: "บันทึกช่วงเวลาและเรียนรู้เทคนิคการถ่ายภาพ",
    category: "arts",
    coverImage: "/photography-camera-exhibition.jpg",
    memberCount: 92,
    createdAt: "2024-02-10",
  },
  {
    id: "6",
    name: "Coding Club",
    nameEn: "Coding Club",
    nameTh: "ชมรมเขียนโปรแกรม",
    description: "Learn programming and build amazing projects",
    descriptionEn: "Learn programming and build amazing projects",
    descriptionTh: "เรียนรู้การเขียนโปรแกรมและสร้างโปรเจกต์ที่น่าทึ่ง",
    category: "technology",
    coverImage: "/coding-programming-hackathon.jpg",
    memberCount: 134,
    createdAt: "2024-01-05",
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    clubId: "1",
    title: "Art Exhibition 2025",
    titleEn: "Art Exhibition 2025",
    titleTh: "นิทรรศการศิลปะ 2025",
    description: "Annual art exhibition showcasing student works",
    descriptionEn: "Annual art exhibition showcasing student works",
    descriptionTh: "นิทรรศการศิลปะประจำปีแสดงผลงานนักศึกษา",
    coverImage: "/art-exhibition-gallery.png",
    date: "2025-03-15",
    time: "10:00 AM",
    location: "Art Gallery, Building 3",
    locationEn: "Art Gallery, Building 3",
    locationTh: "หอศิลป์ อาคาร 3",
    capacity: 200,
    registeredCount: 87,
    category: "cultural",
    tags: ["art", "exhibition", "culture"],
    status: "upcoming",
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    clubId: "2",
    title: "Inter-University Football Tournament",
    titleEn: "Inter-University Football Tournament",
    titleTh: "การแข่งขันฟุตบอลระหว่างมหาวิทยาลัย",
    description: "Compete with other universities in the regional championship",
    descriptionEn: "Compete with other universities in the regional championship",
    descriptionTh: "แข่งขันกับมหาวิทยาลัยอื่นในชิงแชมป์ภูมิภาค",
    coverImage: "/football-tournament-stadium.jpg",
    date: "2025-04-20",
    time: "2:00 PM",
    location: "MFU Stadium",
    locationEn: "MFU Stadium",
    locationTh: "สนามกีฬา มฟล.",
    capacity: 500,
    registeredCount: 234,
    category: "sports",
    tags: ["football", "sports", "competition"],
    status: "upcoming",
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    clubId: "3",
    title: "Dance Workshop",
    titleEn: "Dance Workshop",
    titleTh: "เวิร์คช็อปเต้น",
    description: "Learn contemporary dance techniques from professional instructors",
    descriptionEn: "Learn contemporary dance techniques from professional instructors",
    descriptionTh: "เรียนรู้เทคนิคการเต้นร่วมสมัยจากผู้สอนมืออาชีพ",
    coverImage: "/dance-workshop-studio.jpg",
    date: "2025-03-25",
    time: "4:00 PM",
    location: "Dance Studio, Building 5",
    locationEn: "Dance Studio, Building 5",
    locationTh: "สตูดิโอเต้น อาคาร 5",
    capacity: 30,
    registeredCount: 28,
    category: "workshop",
    tags: ["dance", "workshop", "arts"],
    status: "upcoming",
    createdAt: "2025-01-20",
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    type: "announcement",
    title: "New Club Registration Open!",
    description: "Register your club for the 2025 academic year. Deadline: March 31st",
    date: "2025-01-14",
    likes: 234,
    comments: 45,
    shares: 12,
  },
  {
    id: "2",
    type: "achievement",
    title: "Congrats @CollectedView!",
    description: "Our dance crew won first place at the National Dance Competition",
    image: "/dance-trophy-celebration.jpg",
    clubId: "3",
    clubName: "Dance Crew",
    date: "2025-01-13",
    likes: 567,
    comments: 89,
    shares: 34,
  },
  {
    id: "3",
    type: "event",
    title: "Find Your Point Today!",
    description: "Join us for the annual sports day. Multiple activities and competitions await!",
    image: "/sports-day-university-field.jpg",
    clubId: "2",
    clubName: "Sports Club",
    date: "2025-01-12",
    likes: 432,
    comments: 67,
    shares: 23,
  },
]
