import type { Club, Event, Activity } from "./types"

export const mockClubs: Club[] = [
  {
    id: "1",
    name: "Laced of ART",
    nameEn: "Laced of ART",
    nameTh: "ชมรมศิลปะ",
    description: "Applied Artificial Technology Club - Exploring the intersection of art and technology",
    descriptionEn: "Applied Artificial Technology Club - Exploring the intersection of art and technology",
    descriptionTh: "ชมรมเทคโนโลยีศิลปะประยุกต์ - สำรวจจุดตัดระหว่างศิลปะและเทคโนโลยี",
    category: "arts",
    coverImage: "/art-technology-club-banner.jpg",
    logo: "/art-tech-logo-gold.jpg",
    memberCount: 156,
    contactEmail: "lacedofart@mfu.ac.th",
    socialLinks: {
      facebook: "https://facebook.com/lacedofart",
      instagram: "https://instagram.com/lacedofart",
    },
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    name: "MFU Football Club",
    nameEn: "MFU Football Club",
    nameTh: "ชมรมฟุตบอล มฟล.",
    description: "Competitive football club representing MFU in inter-university tournaments",
    descriptionEn: "Competitive football club representing MFU in inter-university tournaments",
    descriptionTh: "ชมรมฟุตบอลแข่งขันเป็นตัวแทน มฟล. ในการแข่งขันระหว่างมหาวิทยาลัย",
    category: "sports",
    coverImage: "/university-football-team-stadium.jpg",
    memberCount: 89,
    createdAt: "2024-01-10",
  },
  {
    id: "3",
    name: "Dance Crew",
    nameEn: "Dance Crew",
    nameTh: "ชมรมเต้น",
    description: "Modern and traditional dance performances",
    descriptionEn: "Modern and traditional dance performances",
    descriptionTh: "การแสดงเต้นสมัยใหม่และแบบดั้งเดิม",
    category: "arts",
    coverImage: "/dance-performance-stage-lights.jpg",
    memberCount: 67,
    createdAt: "2024-02-01",
  },
  {
    id: "4",
    name: "Music Band",
    nameEn: "Music Band",
    nameTh: "ชมรมดนตรี",
    description: "Live music performances and jam sessions",
    descriptionEn: "Live music performances and jam sessions",
    descriptionTh: "การแสดงดนตรีสดและเซสชั่นแจม",
    category: "music",
    coverImage: "/band-performance-concert.jpg",
    memberCount: 45,
    createdAt: "2024-01-20",
  },
  {
    id: "5",
    name: "Photography Club",
    nameEn: "Photography Club",
    nameTh: "ชมรมถ่ายภาพ",
    description: "Capturing moments and learning photography techniques",
    descriptionEn: "Capturing moments and learning photography techniques",
    descriptionTh: "บันทึกช่วงเวลาและเรียนรู้เทคนิคการถ่ายภาพ",
    category: "arts",
    coverImage: "/photography-camera-exhibition.jpg",
    memberCount: 92,
    createdAt: "2024-02-10",
  },
  {
    id: "6",
    name: "Coding Club",
    nameEn: "Coding Club",
    nameTh: "ชมรมเขียนโปรแกรม",
    description: "Learn programming and build amazing projects",
    descriptionEn: "Learn programming and build amazing projects",
    descriptionTh: "เรียนรู้การเขียนโปรแกรมและสร้างโปรเจกต์ที่น่าทึ่ง",
    category: "technology",
    coverImage: "/coding-programming-hackathon.jpg",
    memberCount: 134,
    createdAt: "2024-01-05",
  },
  {
    id: "7",
    name: "Robotics Club",
    nameEn: "Robotics Club",
    nameTh: "ชมรมหุ่นยนต์",
    description: "Design, build, and program robots for competitions and innovation",
    descriptionEn: "Design, build, and program robots for competitions and innovation",
    descriptionTh: "ออกแบบ สร้าง และเขียนโปรแกรมหุ่นยนต์เพื่อการแข่งขันและนวัตกรรม",
    category: "technology",
    coverImage: "/placeholder.jpg",
    memberCount: 78,
    createdAt: "2024-01-25",
  },
  {
    id: "8",
    name: "Debate Society",
    nameEn: "Debate Society",
    nameTh: "ชมรมอภิปราย",
    description: "Enhance critical thinking and public speaking through competitive debates",
    descriptionEn: "Enhance critical thinking and public speaking through competitive debates",
    descriptionTh: "พัฒนาการคิดเชิงวิพากษ์และการพูดในที่สาธารณะผ่านการอภิปรายแข่งขัน",
    category: "arts",
    coverImage: "/placeholder.jpg",
    memberCount: 52,
    createdAt: "2024-02-05",
  },
  {
    id: "9",
    name: "Basketball Team",
    nameEn: "Basketball Team",
    nameTh: "ทีมบาสเก็ตบอล",
    description: "Competitive basketball team training for university leagues",
    descriptionEn: "Competitive basketball team training for university leagues",
    descriptionTh: "ทีมบาสเก็ตบอลแข่งขันฝึกซ้อมสำหรับลีกมหาวิทยาลัย",
    category: "sports",
    coverImage: "/placeholder.jpg",
    memberCount: 48,
    createdAt: "2024-02-12",
  },
  {
    id: "10",
    name: "Choir Club",
    nameEn: "Choir Club",
    nameTh: "ชมรมคณะนักร้องประสานเสียง",
    description: "Vocal harmony and choir performances for university events",
    descriptionEn: "Vocal harmony and choir performances for university events",
    descriptionTh: "การร้องประสานเสียงและการแสดงสำหรับกิจกรรมมหาวิทยาลัย",
    category: "music",
    coverImage: "/placeholder.jpg",
    memberCount: 65,
    createdAt: "2024-01-18",
  },
  {
    id: "11",
    name: "Environmental Club",
    nameEn: "Environmental Club",
    nameTh: "ชมรมสิ่งแวดล้อม",
    description: "Promoting sustainability and environmental awareness on campus",
    descriptionEn: "Promoting sustainability and environmental awareness on campus",
    descriptionTh: "ส่งเสริมความยั่งยืนและการรับรู้ด้านสิ่งแวดล้อมในมหาวิทยาลัย",
    category: "arts",
    coverImage: "/placeholder.jpg",
    memberCount: 103,
    createdAt: "2024-01-12",
  },
  {
    id: "12",
    name: "Badminton Club",
    nameEn: "Badminton Club",
    nameTh: "ชมรมแบดมินตัน",
    description: "Recreational and competitive badminton for all skill levels",
    descriptionEn: "Recreational and competitive badminton for all skill levels",
    descriptionTh: "แบดมินตันเพื่อการพักผ่อนและแข่งขันสำหรับทุกระดับทักษะ",
    category: "sports",
    coverImage: "/placeholder.jpg",
    memberCount: 71,
    createdAt: "2024-02-08",
  },
  {
    id: "13",
    name: "Film Production Club",
    nameEn: "Film Production Club",
    nameTh: "ชมรมผลิตภาพยนตร์",
    description: "Create and produce short films and video content",
    descriptionEn: "Create and produce short films and video content",
    descriptionTh: "สร้างและผลิตภาพยนตร์สั้นและเนื้อหาวิดีโอ",
    category: "arts",
    coverImage: "/placeholder.jpg",
    memberCount: 59,
    createdAt: "2024-01-30",
  },
  {
    id: "14",
    name: "AI & Machine Learning Club",
    nameEn: "AI & Machine Learning Club",
    nameTh: "ชมรม AI และแมชชีนเลิร์นนิง",
    description: "Explore artificial intelligence and machine learning technologies",
    descriptionEn: "Explore artificial intelligence and machine learning technologies",
    descriptionTh: "สำรวจเทคโนโลยีปัญญาประดิษฐ์และแมชชีนเลิร์นนิง",
    category: "technology",
    coverImage: "/placeholder.jpg",
    memberCount: 112,
    createdAt: "2024-02-15",
  },
  {
    id: "15",
    name: "Jazz Ensemble",
    nameEn: "Jazz Ensemble",
    nameTh: "วงดนตรีแจ๊ส",
    description: "Jazz music performance and improvisation workshops",
    descriptionEn: "Jazz music performance and improvisation workshops",
    descriptionTh: "การแสดงดนตรีแจ๊สและเวิร์คช็อปการด้นสด",
    category: "music",
    coverImage: "/placeholder.jpg",
    memberCount: 38,
    createdAt: "2024-01-22",
  },
  {
    id: "16",
    name: "Swimming Team",
    nameEn: "Swimming Team",
    nameTh: "ทีมว่ายน้ำ",
    description: "Competitive swimming and water sports training",
    descriptionEn: "Competitive swimming and water sports training",
    descriptionTh: "การฝึกว่ายน้ำและกีฬาทางน้ำแข่งขัน",
    category: "sports",
    coverImage: "/placeholder.jpg",
    memberCount: 55,
    createdAt: "2024-02-03",
  },
  {
    id: "17",
    name: "Animation Studio",
    nameEn: "Animation Studio",
    nameTh: "สตูดิโอแอนิเมชัน",
    description: "Create 2D and 3D animations and motion graphics",
    descriptionEn: "Create 2D and 3D animations and motion graphics",
    descriptionTh: "สร้างแอนิเมชัน 2D และ 3D และกราฟิกเคลื่อนไหว",
    category: "arts",
    coverImage: "/placeholder.jpg",
    memberCount: 84,
    createdAt: "2024-01-16",
  },
  {
    id: "18",
    name: "Web Development Club",
    nameEn: "Web Development Club",
    nameTh: "ชมรมพัฒนาเว็บไซต์",
    description: "Build modern web applications and learn full-stack development",
    descriptionEn: "Build modern web applications and learn full-stack development",
    descriptionTh: "สร้างเว็บแอปพลิเคชันสมัยใหม่และเรียนรู้การพัฒนาแบบ full-stack",
    category: "technology",
    coverImage: "/placeholder.jpg",
    memberCount: 127,
    createdAt: "2024-01-08",
  },
  {
    id: "19",
    name: "Orchestra Club",
    nameEn: "Orchestra Club",
    nameTh: "ชมรมวงออเคสตรา",
    description: "Classical music performance with full orchestra ensemble",
    descriptionEn: "Classical music performance with full orchestra ensemble",
    descriptionTh: "การแสดงดนตรีคลาสสิกกับวงออเคสตราเต็มวง",
    category: "music",
    coverImage: "/placeholder.jpg",
    memberCount: 72,
    createdAt: "2024-01-28",
  },
  {
    id: "20",
    name: "Table Tennis Club",
    nameEn: "Table Tennis Club",
    nameTh: "ชมรมเทเบิลเทนนิส",
    description: "Ping pong training and friendly tournaments",
    descriptionEn: "Ping pong training and friendly tournaments",
    descriptionTh: "การฝึกปิงปองและการแข่งขันเป็นกันเอง",
    category: "sports",
    coverImage: "/placeholder.jpg",
    memberCount: 63,
    createdAt: "2024-02-18",
  },
]

export const mockEvents: Event[] = [
  {
    id: "1",
    clubId: "1",
    title: "Art Exhibition 2025",
    titleEn: "Art Exhibition 2025",
    titleTh: "นิทรรศการศิลปะ 2025",
    description: "Annual art exhibition showcasing student works",
    descriptionEn: "Annual art exhibition showcasing student works",
    descriptionTh: "นิทรรศการศิลปะประจำปีแสดงผลงานนักศึกษา",
    coverImage: "/art-exhibition-gallery.png",
    date: "2025-03-15",
    time: "10:00 AM",
    location: "Art Gallery, Building 3",
    locationEn: "Art Gallery, Building 3",
    locationTh: "หอศิลป์ อาคาร 3",
    capacity: 200,
    registeredCount: 87,
    category: "cultural",
    tags: ["art", "exhibition", "culture"],
    status: "upcoming",
    createdAt: "2025-01-10",
  },
  {
    id: "2",
    clubId: "2",
    title: "Inter-University Football Tournament",
    titleEn: "Inter-University Football Tournament",
    titleTh: "การแข่งขันฟุตบอลระหว่างมหาวิทยาลัย",
    description: "Compete with other universities in the regional championship",
    descriptionEn: "Compete with other universities in the regional championship",
    descriptionTh: "แข่งขันกับมหาวิทยาลัยอื่นในชิงแชมป์ภูมิภาค",
    coverImage: "/football-tournament-stadium.jpg",
    date: "2025-04-20",
    time: "2:00 PM",
    location: "MFU Stadium",
    locationEn: "MFU Stadium",
    locationTh: "สนามกีฬา มฟล.",
    capacity: 500,
    registeredCount: 234,
    category: "sports",
    tags: ["football", "sports", "competition"],
    status: "upcoming",
    createdAt: "2025-01-15",
  },
  {
    id: "3",
    clubId: "3",
    title: "Dance Workshop",
    titleEn: "Dance Workshop",
    titleTh: "เวิร์คช็อปเต้น",
    description: "Learn contemporary dance techniques from professional instructors",
    descriptionEn: "Learn contemporary dance techniques from professional instructors",
    descriptionTh: "เรียนรู้เทคนิคการเต้นร่วมสมัยจากผู้สอนมืออาชีพ",
    coverImage: "/dance-workshop-studio.jpg",
    date: "2025-03-25",
    time: "4:00 PM",
    location: "Dance Studio, Building 5",
    locationEn: "Dance Studio, Building 5",
    locationTh: "สตูดิโอเต้น อาคาร 5",
    capacity: 30,
    registeredCount: 28,
    category: "workshop",
    tags: ["dance", "workshop", "arts"],
    status: "upcoming",
    createdAt: "2025-01-20",
  },
]

export const mockActivities: Activity[] = [
  {
    id: "1",
    type: "announcement",
    title: "New Club Registration Open!",
    description: "Register your club for the 2025 academic year. Deadline: March 31st",
    date: "2025-01-14",
    likes: 234,
    comments: 45,
    shares: 12,
  },
  {
    id: "2",
    type: "achievement",
    title: "Congrats @CollectedView!",
    description: "Our dance crew won first place at the National Dance Competition",
    image: "/dance-trophy-celebration.jpg",
    clubId: "3",
    clubName: "Dance Crew",
    date: "2025-01-13",
    likes: 567,
    comments: 89,
    shares: 34,
  },
  {
    id: "3",
    type: "event",
    title: "Find Your Point Today!",
    description: "Join us for the annual sports day. Multiple activities and competitions await!",
    image: "/sports-day-university-field.jpg",
    clubId: "2",
    clubName: "Sports Club",
    date: "2025-01-12",
    likes: 432,
    comments: 67,
    shares: 23,
  },
]
